import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(resolve(process.argv[2], 'package.json'));
const { PGlite } = require('@electric-sql/pglite');
const db = new PGlite();
try {
 const sql = await readFile(new URL('../gastos.sql', import.meta.url), 'utf8');
 await db.exec(sql); await db.exec(sql);
 const create = async (date, recurring=true) => (await db.query("insert into gastos(descricao,valor,data,categoria,status,recorrente) values ('Energia',100,$1,'Energia','Pago',$2) returning id,recorrencia_id",[date,recurring])).rows[0];
 const process = async date => Number((await db.query('select processar_gastos_recorrentes($1) as n',[date])).rows[0].n);
 const original = await create('2026-09-08');
 await create('2026-09-08',false);
 assert.equal(await process('2026-10-08'),0);
 assert.equal(await process('2026-10-09'),1);
 assert.equal(await process('2026-10-09'),0);
 assert.equal((await db.query('select status from gastos where id=$1',[original.id])).rows[0].status,'Pago');
 let rows=(await db.query('select status,data::text from gastos where recorrencia_id=$1 order by data',[original.recorrencia_id])).rows;
 assert.deepEqual(rows,[{status:'Pago',data:'2026-09-08'},{status:'Pendente',data:'2026-10-08'}]);
 await db.query("update gastos set status='Pago' where recorrencia_id=$1",[original.recorrencia_id]);
 assert.equal(await process('2026-12-09'),2);
 assert.equal(await process('2026-12-09'),0);
 await db.query('update gastos set valor=150 where id=$1',[original.id]);
 assert.equal(await process('2027-01-09'),1);
 assert.equal(Number((await db.query("select valor from gastos where data='2027-01-08'")).rows[0].valor),150);
 assert.equal(Number((await db.query("select valor from gastos where data='2026-10-08'")).rows[0].valor),100);
 await db.query('update gastos set recorrente=false where id=$1',[original.id]);
 assert.equal(await process('2027-02-09'),0);
 assert.equal(Number((await db.query('select count(*) as n from gastos where recorrente')).rows[0].n),0);
 const endMonth=await create('2028-01-31');
 assert.equal(await process('2028-02-29'),0);
 assert.equal(await process('2028-03-01'),1);
 assert.equal(await process('2028-03-31'),0);
 assert.equal(await process('2028-04-01'),1);
 rows=(await db.query('select data::text from gastos where recorrencia_id=$1 order by data',[endMonth.recorrencia_id])).rows;
 assert.deepEqual(rows.map(r=>r.data),['2028-01-31','2028-02-29','2028-03-31']);
 await assert.rejects(db.query("insert into gastos(descricao,valor,data,categoria,status,recorrencia_id,competencia) values ('Duplicada',100,'2028-03-31','Energia','Pendente',$1,'2028-03-01')",[endMonth.recorrencia_id]));
 await db.query('delete from gastos where id=$1',[endMonth.id]);
 assert.equal(await process('2028-05-01'),0);
 assert.equal(Number((await db.query('select count(*) as n from gastos where recorrencia_id=$1',[endMonth.recorrencia_id])).rows[0].n),2);
 await db.exec('create role recurrence_test; grant usage on schema public to recurrence_test; grant select,insert,update,delete on gastos to recurrence_test; set role recurrence_test');
 await assert.rejects(process('2030-01-01'));
 await create('2026-09-08');
 console.log('OK: recorrência, histórico, vencimento, meses curtos/ano bissexto, recuperação, edição, cancelamento, exclusão, unicidade e permissões.');
} finally { await db.close(); }
